### ISSUE TITLE
DMS MVP - User logout

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-dms-demo#18]
As the user of the DMS, I want to be able to log out, so others can not reorganize my documents and steal my life while i am afk.

## Acceptance criteria
- [ ] The user clicks on logout, and we log them out.

## Questions
- [ ] Where do you think we should put the logout button? 👍

**Comment by herflis** [comment]
I've put a dropdown menu in the header for displaying it, @borsi check it on the demo site pls
