### ISSUE TITLE
DMS MVP - Rename contents

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-dms-demo#20]
As a DMS user, I want to be able to rename my Documents and Folders

## Acceptance crit:
- [x] Clicking on the 'Rename' option, we can rename the content, by providing it's new name in-place
- [ ] ~~Slow double-clicking on the content, we can rename it.~~

## Questions
- Appearence: how should it look like?

**Comment by herflis** [comment]
@borsi I think we should re-think this issue because it is in contradiction with the gesture definition table :)
