### ISSUE TITLE
Image missing for preview image generation in progress message

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-dms-demo#268]
![image.png](https://images.zenhubusercontent.com/5af2e69b4b5806bc2bd27313/8e8b66ff-e71d-4087-a08c-f0b599ed2be1)

**Comment by gallayl** [comment]
- [ ] Loader image url should be customized in the DocViewer component
 - [ ] New minor version of the DocViewer should be released
 - [ ] Loader image should be added to the bundle in DMS Demo
 - [ ] DocViewer should be configured with the correct loader URL in DMS Demo
