### ISSUE TITLE
[DMS] Version history and restore version

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-dms-demo#277]
![image](https://user-images.githubusercontent.com/6968860/43632367-3072f04e-9706-11e8-9fa0-572b5bb6ea71.png)

The two buttons are removed, because the blue one is related to another feature (a simple reupload) and should not be here and the 'ok' button is simply unnecesarry because it was only closing the dialog which is possible with clicking away from the dialog or with the delete icon in the top right corner.

**Comment by kultsar** [comment]
- [ ] All lines show the same value in the Modified by column. The last line shows correctly the last modification time and modifier, but all other lines show this value as well, they do not retain their original value.

**Comment by kultsar** [comment]
Just to make sure, had a look, not ok yet.

**Comment by kultsar** [comment]
Thinking about checkin/checkout features... Are they full features as they are now. Let's talk about them.
