### ISSUE TITLE
[DMS] - Generic error & not found pages

### ISSUE THREAD

**Issue by gallayl** [SenseNet/sn-dms-demo#283]
We should create pages with some generic error messages for the following scenarios (similar as for the DocViewer ones):
 - 404 - not found, the content has been moved or you don't have permission to see it
 - 500 - server error, try again later

**Comment by kultsar** [comment]
Issue moved to [SenseNet/sn-client #27](https://github.com/SenseNet/sn-client/issues/27) via [**ZenHub**](https://www.zenhub.com/)
