### ISSUE TITLE
[DMS] - Version history mobile optimization

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-dms-demo#353]

**Comment by kultsar** [comment]
For a short time (half a second) ui displays this:
![image.png](https://images.zenhubusercontent.com/5af2e69b4b5806bc2bd27313/cf07342a-d8c1-407b-8693-92cc3294f772)
... then a blank screen, and it remains blank, cannot escape except for reloading the page:
![image.png](https://images.zenhubusercontent.com/5af2e69b4b5806bc2bd27313/27e4d8c5-a77b-4612-b333-83e6ca9377ad)
