### ISSUE TITLE
Edit properties modifications not saved

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-dms-demo#363]
See also: https://github.com/SenseNet/sensenet/issues/477

A bit arbitrary, as it worked a few hours before, and in some folders (but not in others), but now it seems it just does not work anywhere. Also: might need to move this bug report to another repo.

User: alba (DMS Demo frontend and webpages backend). User submits Edit properties dialogue window, with or without any modifications

Error message on dms frontend:
63 items are undefined
Content Cannot write the CreationDate property because it is read only.

Error message on webpages backend:
An unexpected error occurred, please report the following technical details to your system
Exception type: System.NullReferenceException
Exception message:
Object reference not set to an instance of an object.
Example: https://dmsservice.demo.sensenet.com/Root/Profiles/Public/alba/Document_Library/Books/My%20collection/2018/september/The%20Iliad%20by%20Homer.pdf?action=Edit&back=%2FRoot%2FProfiles%2FPublic%2Falba%2FDocument_Library%2FBooks%2FMy%2520collection%2F2018%2Fseptember

Also, session seems to be destroyed, webpages ui says "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable" on refresh, and system asks fro credentials when loading site url.

**Comment by herflis** [comment]
@kultsar pls add steps to reproduce (I've tried to modify sample-doc's displayname and it works as it should)

**Comment by kultsar** [comment]
Steps to reproduce

Browser I'm using: Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
* Logged in to DMS, opened http://sn-dms-demo-dev.netlify.com/#/documents/
![image](https://user-images.githubusercontent.com/39081660/46296224-2f0fcc00-c59a-11e8-809b-af7907f4e98f.png)

* Run Edit action on Sample-document2.doc
![image](https://user-images.githubusercontent.com/39081660/46296283-4bac0400-c59a-11e8-89e0-9e7ee002b7bf.png)

* Rename from 2 to 3
![image](https://user-images.githubusercontent.com/39081660/46296298-58305c80-c59a-11e8-8462-11ac3ad385ad.png)

* Submit
![image](https://user-images.githubusercontent.com/39081660/46296320-63838800-c59a-11e8-9663-e4e358a8c5cd.png)

* After refresh:
![image](https://user-images.githubusercontent.com/39081660/46296337-70a07700-c59a-11e8-81cb-29bc5f3979eb.png)

* Opening Edit properties again:
![image](https://user-images.githubusercontent.com/39081660/46296365-7eee9300-c59a-11e8-84a4-55d5faf47eb1.png)

**Comment by kultsar** [comment]
This is probably closely connected to this: https://github.com/SenseNet/sn-dms-demo/issues/362

**Comment by kultsar** [comment]
Tried on mobile device as well. Steps are the same, update is not successful.

![image](https://user-images.githubusercontent.com/39081660/46297728-abf07500-c59d-11e8-901e-90ba4c86cf4e.png)
