### ISSUE TITLE
Mobile GUI: Exiting workspace selector without making a selection results in blank document list

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-dms-demo#365]
User clicks workspace selector icon, list appears.
![image](https://user-images.githubusercontent.com/39081660/46107687-4d617a80-c1dc-11e8-926d-6bcb5682b2fa.png)

User changes her mind, clicks a neutral area. UI changes to a partially blank page:
![image.png](https://images.zenhubusercontent.com/5af2e69b4b5806bc2bd27313/13ebf5c1-a926-425f-8d1a-40bbb836ca79)

User feels sad.

**Comment by herflis** [comment]
There's a close icon in the top right corner of the workspace selector to close it but it had a blue color so that it was hidden. I've fixed it to has white color so the selector can be closed using the button and it does not occure any issues in the doclib
