### ISSUE TITLE
DMS MVP - Lazy Registration

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-dms-demo#4]
@borsi commented on [Wed Jul 12 2017](https://github.com/SenseNet/sn-controls-react/issues/5)

As an end user, I want to be able to register on the Sensenet7 - Document management mvp site.

## Acceptance crit:
- [x] The user needs to provide a valid e-mail address
- [x] The correct format is signified with a placeholder
- [x] The user also needs to provide her password in password fields - twice.
- [x] The password needs to be longer than 8 characters, needs to contain numbers, capitals and special characters
- [x] The user gets a relevant error message on the form, when the format is not valid
- [x] In addition to the client-side validation, we - obviously - validate on the server side as well
- [x] When the user clicks on the Register button, it becomes disabled so she can only submit her registration once
- [x] A loader-spinner signifies the loading, when we create the users' content
- [x] One e-mail can only be used once
- [x] When the registration is successful, the user gets to the login page, where she can log in.
- [x] There is a recaptcha on the register form that prevents bots from registering
- [ ] In the future we'd like to store more data about the user
- [x] The user is informed about our cookie policy and privacy policy

## Tracking:
- [ ] A custom event is fired, when the user submits the form.
- send a notification about every registration?

### Talk about
- One e-mail address
- Registration API

## Notes

**Url structure:**
- home: dms.demo.sensenet.com/
- registration: dms.demo.sensenet.com/registration
- login: dms.demo.sensenet.com/login
- profile: dms.demo.sensenet.com/profile

[edit: added initial wf]
![register](https://user-images.githubusercontent.com/632613/28877232-0cd191ca-779c-11e7-98ad-485d9f6220fe.png)

**Comment by herflis** [comment]
@borsi Is the privacy policy page on sensenet.com ok to refer here to or do we need a custom one?

**Comment by borsi** [comment]
It should be okay, we are using the same cookies and requesting for the same type of data here.
