### ISSUE TITLE
DMS MVP - Path picker control

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-dms-demo#69]
![image](https://user-images.githubusercontent.com/6968860/43707219-d133e21e-9967-11e8-8baf-193b6a9cd6d6.png)

**Comment by herflis** [comment]
@kultsar I'm not able to reproduce this issue you've mentioned above

**Comment by kultsar** [comment]
Yes, something changed, it was more difficult to reproduce for me as well. It may not even be an issue strictly connected to the path picker. The point is that the window remembers if it was closed with the up button or the logo in the top left corner. Anyway, now it can be reproduced this way:

* initiate copy/move dialogue
* keep clicking the up button in the dialogue window until you get to the top of the directory structure (note: the up button now will change to the sensenet logo)
* click cancel
* initiate another copy/move operation - up button is replaced by sensenet logo

On the other hand, if I close/cancel the window with the up button there in the corner, then next time the up button will also be there. So the window remembers if it was closed with the up button or the logo in the top left corner.
