### ISSUE TITLE
DMS MVP - RT Office edit (WOPI)

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-dms-demo#70]
As a DMS user, I want to be able to collaboratively edit any office document I have the permission to - in the DMS.

## Acceptance crit:
- [ ] When double clicking on an office document (doc{x}, xls{x}, ppt{x}), an editor opens, where I can edit the document in real time.
- [ ] The changes are saved back on the document

## Questions
- Can we have named versions?
- Can we compare versions with each other?
etc

**Comment by tusmester** [comment]
Maybe we should go easy and implement viewing functionality first (as an initial issue).
Comparing versions is a different (additional) feature, I believe it is not related to WOPI.

**Comment by kultsar** [comment]
Issue moved to [SenseNet/sn-client #53](https://github.com/SenseNet/sn-client/issues/53) via [**ZenHub**](https://www.zenhub.com/)
