### ISSUE TITLE
DMS MVP - Demo import needs

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-dms-demo#9]
- [x] We need a default user under the Public domain (alba /w the loginname alba@sensenet.com will be perfect)
  - [x] add avatar image
  - [x] add profile for her and template (both), see comments below
- [x] localhost should be also added to the Portal.settings as AllowedOriginDomain (done, but only localhost, without a port)
- [x] the owner group should get full control on the profile ws

**Comment by tusmester** [comment]
A couple of questions:
- we have to figure out the group memberships of this 'public' alba - and also the group memberships of newly registered public users. Currently they have none.
- does this public alba need a profile ws?

**Comment by herflis** [comment]
- yes, she should have a profile ws
- and it would be nice if she could have an avatar
- we could check the permissions, after the jwt fixes are published
- the doclib in the profile contenttemplate should have at least three built-in children
-- a smartfolder with the name _Shared_
-- a folder named _Sample Folder_
-- a word document with name _Sample-document.docx_/_Lorem-ipsum.docx_

**Comment by herflis** [comment]
the owner group should get full control on the profile ws (it works on demo.sensenet.com but not on the dmsservices)
